runtime: go111

main: main

handlers:

# All URLs are handled by the Go application script
- url: /.*
  script: auto

env_variables:
  GCP_PROJECT: 'sonomy'

# @see https://stackoverflow.com/questions/27088363/how-to-ignore-changes-in-some-folders-when-developing-locally
skip_files:
# default from GAE
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$

# custom entries

# dev-related files
- ptvsd
- pydev_startup.py
- .pylintrc
- .data
- .vscode
- /app/docker/data(/.*)?

# version control files
- .git
- .gitignore
- .gitattributes

# non-application files
- README.md
- ^(.*/)?.*\.mwb(.bak)?$ # workbench models