version: '3'

services:
  go:
    build:
      context: .
      args:
       GOLANG_VERSION: 1.11.10
    environment:
      - "SHELL=/bin/bash"
      - "GO11MODULE=on"
      - DATASTORE_PROJECT_ID
      - CLOUDSDK_CORE_PROJECT
      - GOOGLE_APPLICATION_CREDENTIALS
    volumes:
      - .:/app
      - /go
    ports:
      - 8082:8082
      - 8000:8000
    working_dir: /app
    command: ./run