version: '3'

services:
  datastore:
    image: google/cloud-sdk:latest
    hostname: datastore
    expose:
      - 8081
    command: gcloud beta emulators datastore start --project=sonomy --host-port datastore:8081 --data-dir=/app/docker/data/datastore
    volumes:
      - .:/app:cached

  go:
    build:
      context: docker/.
    environment:
      - "SHELL=/bin/bash"
      - "GO11MODULE=on"
    volumes:
      - .:/app:cached
      - ./docker/data/go:/go:cached
    ports:
      - 8080:8080
      - 8000:8000
    working_dir: /app
    command: sleep infinity
    depends_on:
      - datastore
