version: '3'

services:
  datastore:
    image: google/cloud-sdk:latest
    hostname: datastore
    expose:
      - 8081
    command: gcloud beta emulators datastore start --project=sonomy --host-port datastore:8081
    volumes:
      - .:/app

  go:
    build:
      context: docker/.
    environment:
      - "SHELL=/bin/bash"
      - "GO11MODULE=on"
    volumes:
      - .:/app
      - /go
    ports:
      - 8080:8080
      - 8000:8000
    working_dir: /app
    #command: ./run
    command: sleep infinity
    depends_on:
      - datastore
