#!/bin/bash

# Usualy $(gcloud beta emulators datastore env-init --data-dir=./data) but specify for docker
export DATASTORE_EMULATOR_HOST=datastore:8081
export DATASTORE_EMULATOR_HOST_PATH=datastore:8081/datastore
export DATASTORE_HOST=http://datastore:8081

# Maybe specify on docker-compose(or .env)
# export DATASTORE_PROJECT_ID=

echo '> main start'
dev_appserver.py app.yaml --host=0.0.0.0 --admin_host=0.0.0.0